data:
  nih_path: "/kaggle/input/datasets/khanfashee/nih-chest-x-ray-14-224x224-resized"
  shenzhen_path: "/kaggle/input/datasets/raddar/tuberculosis-chest-xrays-shenzhen/images"
  montgomery_path: "/kaggle/input/datasets/raddar/tuberculosis-chest-xrays-montgomery"
  processed_dir: "/kaggle/working/Fed-SSL-TB/data/processed"
  image_size: 224
  num_hospitals: 10
  split_strategy: non_iid
  split_alpha: 1.0

model:
  backbone: "vit_tiny"
  embed_dim: 192
  mask_ratio: 0.80
  decoder_depth: 4

ssl:
  epochs_per_round: 2
  batch_size: 16
  lr: 1.0e-3

federated:
  rounds: 30
  aggregation: fedprox
  fedprox_mu: 0.01
  min_client_samples: 500

few_shot:
  shots_per_class: 5
  train_queries_per_class: 5
  seed: 42

loss:
  lambda_mae: 0.70
  lambda_proto: 0.30

logging:
  log_dir: "/kaggle/working/Fed-SSL-TB/experiments/logs"
  checkpoint_dir: "/kaggle/working/Fed-SSL-TB/experiments/checkpoints"